name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.zip
    
    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Authenticate with ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop (xrdp)
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

        # Allow RDP through the firewall
        sudo ufw allow 3389/tcp

        # Set password for the default user (ubuntu in GitHub Actions)
        echo "ubuntu:P@ssw0rd!" | sudo chpasswd

    - name: Create ngrok tunnel to remote desktop
      run: ./ngrok tcp 3389
